# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: deliverytime-svc
spec:
  type: NodePort
  selector:
    app: deliverytime
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000